/* ANG HR v0.6.0 */
(function(){
'use strict';
var V='0.6.0',K_RULE='ang_hr_v060_rule',K_SEL='ang_hr_v060_selection',K_SUP='ang_hr_v060_support',K_EC='ang_hr_v060_emergency';
function q(id){return document.getElementById(id)}
function rd(k,d){try{return JSON.parse(localStorage.getItem(k)||'null')||d}catch(e){return d}}
function wr(k,v){localStorage.setItem(k,JSON.stringify(v))}
function emp(){return String((window.CTX&&CTX.id)||localStorage.getItem('ang_employee_id')||'').toUpperCase()}
function esc(v){return String(v||'').replace(/[&<>\"]/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'})[c]})}
function monthNow(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function days(m){var p=m.split('-');return new Date(+p[0],+p[1],0).getDate()}
function style(){var s=document.createElement('style');s.textContent='.v060-card{background:var(--card,#fff);border-radius:22px;padding:14px;margin-bottom:10px;box-shadow:0 8px 24px rgba(0,0,0,.05)}.v060-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.v060-days{display:grid;grid-template-columns:repeat(7,minmax(40px,1fr));gap:6px;overflow-x:auto}.v060-day{border:0;border-radius:13px;min-height:48px;background:var(--soft,#eee);font-weight:900}.v060-day.on{background:var(--emp-gradient,#4A90E2);color:#fff}.v060-note{font-size:12px;color:var(--muted,#666);line-height:1.5;margin:6px 0 10px}.v060-item{background:var(--soft,#eee);border-radius:14px;padding:10px;margin-top:8px;font-size:12px;line-height:1.5}.v060-ver{position:fixed;left:8px;bottom:8px;z-index:999;font-size:9px;opacity:.55}';document.head.appendChild(s);var b=document.createElement('div');b.className='v060-ver';b.textContent='ANG HR v'+V;document.body.appendChild(b)}
function addAdminLeave(){var box=q('monthRuleBox');if(!box||q('v060Month'))return;box.insertAdjacentHTML('beforeend','<label class="label">選休月份</label><input type="month" id="v060Month"><div class="v060-grid"><div><label class="label">最多可選天數</label><input type="number" id="v060Max" value="8" min="1" max="31"></div><div><label class="label">截止時間</label><input type="datetime-local" id="v060Deadline"></div></div><div id="v060AdminDays" class="v060-days"></div>');var r=rd(K_RULE,{mode:'week',month:monthNow(),max:8,deadline:''});q('v060Month').value=r.month;q('v060Max').value=r.max;q('v060Deadline').value=r.deadline||'';function draw(){var m=q('v060Month').value||monthNow(),h='';for(var i=1;i<=days(m);i++)h+='<button type="button" class="v060-day">'+i+'</button>';q('v060AdminDays').innerHTML=h}draw();q('v060Month').onchange=draw;var oldSave=window.savePreselectSettingsFromUI;window.savePreselectSettingsFromUI=function(){wr(K_RULE,{mode:window.preselectMode==='month'?'month':'week',month:q('v060Month').value||monthNow(),max:+q('v060Max').value||8,deadline:q('v060Deadline').value||''});if(oldSave)oldSave.apply(this,arguments)};var oldSet=window.setPreselectMode;window.setPreselectMode=function(m){window.preselectMode=m==='month'?'month':'week';var r=rd(K_RULE,{});r.mode=window.preselectMode;wr(K_RULE,r);if(oldSet)oldSet.apply(this,arguments)}}
function addEmployeeLeave(){if(q('v060EmployeeLeave'))return;var host=q('page-schedule')||q('page-leave')||q('page-home');if(!host)return;var c=document.createElement('div');c.id='v060EmployeeLeave';c.className='v060-card';host.appendChild(c);var r=rd(K_RULE,{mode:'week',month:monthNow(),max:8}),all=rd(K_SEL,{}),id=emp()||'UNKNOWN',sel=(all[id]&&all[id].dates)||[],list=[];if(r.mode==='month'){for(var i=1;i<=days(r.month);i++)list.push(r.month+'-'+String(i).padStart(2,'0'))}else{var d=new Date(),n=d.getDay(),x=(n===0?-6:1-n);d.setDate(d.getDate()+x);for(var j=0;j<7;j++){var z=new Date(d);z.setDate(d.getDate()+j);list.push(z.toISOString().slice(0,10))}}c.innerHTML='<h3 style="margin-top:0">'+(r.mode==='month'?'月選休':'週選休')+'</h3><div class="v060-note">最多可選 '+r.max+' 天'+(r.deadline?'｜截止 '+r.deadline.replace('T',' '):'')+'</div><div id="v060EmpDays" class="v060-days"></div><button class="btn-main" id="v060Submit">送出選休</button>';var b=q('v060EmpDays');list.forEach(function(ds){var bt=document.createElement('button');bt.type='button';bt.className='v060-day'+(sel.indexOf(ds)>-1?' on':'');bt.textContent=+ds.slice(-2);bt.onclick=function(){var i=sel.indexOf(ds);if(i>-1)sel.splice(i,1);else if(sel.length<r.max)sel.push(ds);else return alert('已達可選天數上限');bt.classList.toggle('on')};b.appendChild(bt)});q('v060Submit').onclick=function(){all[id]={mode:r.mode,period:r.month,dates:sel.slice().sort(),updatedAt:new Date().toISOString()};wr(K_SEL,all);alert('選休已儲存')}}
function addSupport(){var anchor=q('clockLocationRadius');if(!anchor||q('v060Support'))return;var c=document.createElement('div');c.id='v060Support';c.className='v060-card';c.innerHTML='<h3 style="margin-top:0">支援｜臨時打卡點</h3><div class="v060-note">指定員工、地點與時段；到期自動恢復原分店。</div><div class="v060-grid"><input id="v060SEmp" placeholder="員工編號"><input id="v060SName" placeholder="支援分店／地點"></div><div class="v060-grid"><input type="datetime-local" id="v060SFrom"><input type="datetime-local" id="v060STo"></div><div class="v060-grid"><input type="number" step="0.000001" id="v060SLat" placeholder="緯度"><input type="number" step="0.000001" id="v060SLng" placeholder="經度"></div><input type="number" id="v060SRadius" value="200" placeholder="允許距離（公尺）"><button class="btn-main" id="v060SSave">建立支援打卡點</button><div id="v060SList"></div>';var card=anchor.closest('.card');card.parentNode.insertBefore(c,card.nextSibling);function render(){q('v060SList').innerHTML=rd(K_SUP,[]).slice().reverse().map(function(a){return '<div class="v060-item"><b>'+esc(a.employeeId)+'｜'+esc(a.name)+'</b><br>'+a.from.replace('T',' ')+' ～ '+a.to.replace('T',' ')+'<br>半徑 '+a.radius+'m</div>'}).join('')||'<div class="v060-item">目前沒有支援指派</div>'}q('v060SSave').onclick=function(){var a={id:'SUP-'+Date.now(),employeeId:q('v060SEmp').value.trim().toUpperCase(),name:q('v060SName').value.trim(),from:q('v060SFrom').value,to:q('v060STo').value,lat:+q('v060SLat').value,lng:+q('v060SLng').value,radius:+q('v060SRadius').value||200};if(!a.employeeId||!a.name||!a.from||!a.to||!isFinite(a.lat)||!isFinite(a.lng))return alert('支援資料未填完整');var x=rd(K_SUP,[]);x.push(a);wr(K_SUP,x);render();alert('支援打卡點已建立')};render()}
function addEmergency(){var n=q('peopleName');if(!n||q('v060ECName'))return;var row=n.closest('.field-row');var d=document.createElement('div');d.innerHTML='<div class="v060-grid"><input id="v060Phone" placeholder="手機 *"><input id="v060Email" type="email" placeholder="Email *"></div><div class="v060-grid"><input id="v060ECName" placeholder="緊急聯絡人姓名 *"><select id="v060ECRel"><option>母親</option><option>父親</option><option>配偶</option><option>伴侶</option><option>兄弟姊妹</option><option>親屬</option><option>朋友</option><option>其他</option></select></div><input id="v060ECOther" placeholder="其他關係名稱" style="display:none"><input id="v060ECPhone" placeholder="緊急聯絡電話 *"><div class="v060-note">每次修改新增歷史版本，不覆蓋舊資料。</div>';row.parentNode.insertBefore(d,row.nextSibling);q('v060ECRel').onchange=function(){q('v060ECOther').style.display=this.value==='其他'?'block':'none'};var old=window.peopleSave;window.peopleSave=function(){var id=(q('peopleEmpId').value||window.peopleCurrentId||'').toUpperCase(),name=q('v060ECName').value.trim(),rel=q('v060ECRel').value==='其他'?q('v060ECOther').value.trim():q('v060ECRel').value,phone=q('v060ECPhone').value.trim();if(!q('v060Phone').value.trim()||!q('v060Email').value.trim()||!name||!rel||!phone)return alert('手機、Email、緊急聯絡人姓名、關係、電話皆為必填');var h=rd(K_EC,{}),a=h[id]||[],last=a[a.length-1];if(!last||last.name!==name||last.rel!==rel||last.phone!==phone){if(last&&!last.until)last.until=new Date().toISOString();a.push({name:name,rel:rel,phone:phone,from:new Date().toISOString(),until:'',changedBy:emp()});h[id]=a;wr(K_EC,h)}if(old)return old.apply(this,arguments)}}
function fixNav(){var home=q('fab-home'),wrap=q('fabWrap');if(!home||!wrap)return;home.onclick=function(){wrap.classList.toggle('is-collapsed')};document.querySelectorAll('.fab-sat').forEach(function(b){b.addEventListener('click',function(){wrap.classList.add('is-collapsed')})})}
function init(){style();addAdminLeave();addEmployeeLeave();addSupport();addEmergency();fixNav()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();